/*
Lidarr

Lidarr API docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// ArtistMetadataLazyLoaded struct for ArtistMetadataLazyLoaded
type ArtistMetadataLazyLoaded struct {
	Value *ArtistMetadata `json:"value,omitempty"`
	IsLoaded *bool `json:"isLoaded,omitempty"`
}

// NewArtistMetadataLazyLoaded instantiates a new ArtistMetadataLazyLoaded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtistMetadataLazyLoaded() *ArtistMetadataLazyLoaded {
	this := ArtistMetadataLazyLoaded{}
	return &this
}

// NewArtistMetadataLazyLoadedWithDefaults instantiates a new ArtistMetadataLazyLoaded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtistMetadataLazyLoadedWithDefaults() *ArtistMetadataLazyLoaded {
	this := ArtistMetadataLazyLoaded{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ArtistMetadataLazyLoaded) GetValue() ArtistMetadata {
	if o == nil || isNil(o.Value) {
		var ret ArtistMetadata
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistMetadataLazyLoaded) GetValueOk() (*ArtistMetadata, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ArtistMetadataLazyLoaded) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given ArtistMetadata and assigns it to the Value field.
func (o *ArtistMetadataLazyLoaded) SetValue(v ArtistMetadata) {
	o.Value = &v
}

// GetIsLoaded returns the IsLoaded field value if set, zero value otherwise.
func (o *ArtistMetadataLazyLoaded) GetIsLoaded() bool {
	if o == nil || isNil(o.IsLoaded) {
		var ret bool
		return ret
	}
	return *o.IsLoaded
}

// GetIsLoadedOk returns a tuple with the IsLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistMetadataLazyLoaded) GetIsLoadedOk() (*bool, bool) {
	if o == nil || isNil(o.IsLoaded) {
    return nil, false
	}
	return o.IsLoaded, true
}

// HasIsLoaded returns a boolean if a field has been set.
func (o *ArtistMetadataLazyLoaded) HasIsLoaded() bool {
	if o != nil && !isNil(o.IsLoaded) {
		return true
	}

	return false
}

// SetIsLoaded gets a reference to the given bool and assigns it to the IsLoaded field.
func (o *ArtistMetadataLazyLoaded) SetIsLoaded(v bool) {
	o.IsLoaded = &v
}

func (o ArtistMetadataLazyLoaded) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !isNil(o.IsLoaded) {
		toSerialize["isLoaded"] = o.IsLoaded
	}
	return json.Marshal(toSerialize)
}

type NullableArtistMetadataLazyLoaded struct {
	value *ArtistMetadataLazyLoaded
	isSet bool
}

func (v NullableArtistMetadataLazyLoaded) Get() *ArtistMetadataLazyLoaded {
	return v.value
}

func (v *NullableArtistMetadataLazyLoaded) Set(val *ArtistMetadataLazyLoaded) {
	v.value = val
	v.isSet = true
}

func (v NullableArtistMetadataLazyLoaded) IsSet() bool {
	return v.isSet
}

func (v *NullableArtistMetadataLazyLoaded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtistMetadataLazyLoaded(val *ArtistMetadataLazyLoaded) *NullableArtistMetadataLazyLoaded {
	return &NullableArtistMetadataLazyLoaded{value: val, isSet: true}
}

func (v NullableArtistMetadataLazyLoaded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtistMetadataLazyLoaded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


