/*
Lidarr

Lidarr API docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// TrackFileLazyLoaded struct for TrackFileLazyLoaded
type TrackFileLazyLoaded struct {
	Value *TrackFile `json:"value,omitempty"`
	IsLoaded *bool `json:"isLoaded,omitempty"`
}

// NewTrackFileLazyLoaded instantiates a new TrackFileLazyLoaded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackFileLazyLoaded() *TrackFileLazyLoaded {
	this := TrackFileLazyLoaded{}
	return &this
}

// NewTrackFileLazyLoadedWithDefaults instantiates a new TrackFileLazyLoaded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackFileLazyLoadedWithDefaults() *TrackFileLazyLoaded {
	this := TrackFileLazyLoaded{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *TrackFileLazyLoaded) GetValue() TrackFile {
	if o == nil || isNil(o.Value) {
		var ret TrackFile
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackFileLazyLoaded) GetValueOk() (*TrackFile, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *TrackFileLazyLoaded) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given TrackFile and assigns it to the Value field.
func (o *TrackFileLazyLoaded) SetValue(v TrackFile) {
	o.Value = &v
}

// GetIsLoaded returns the IsLoaded field value if set, zero value otherwise.
func (o *TrackFileLazyLoaded) GetIsLoaded() bool {
	if o == nil || isNil(o.IsLoaded) {
		var ret bool
		return ret
	}
	return *o.IsLoaded
}

// GetIsLoadedOk returns a tuple with the IsLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackFileLazyLoaded) GetIsLoadedOk() (*bool, bool) {
	if o == nil || isNil(o.IsLoaded) {
    return nil, false
	}
	return o.IsLoaded, true
}

// HasIsLoaded returns a boolean if a field has been set.
func (o *TrackFileLazyLoaded) HasIsLoaded() bool {
	if o != nil && !isNil(o.IsLoaded) {
		return true
	}

	return false
}

// SetIsLoaded gets a reference to the given bool and assigns it to the IsLoaded field.
func (o *TrackFileLazyLoaded) SetIsLoaded(v bool) {
	o.IsLoaded = &v
}

func (o TrackFileLazyLoaded) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !isNil(o.IsLoaded) {
		toSerialize["isLoaded"] = o.IsLoaded
	}
	return json.Marshal(toSerialize)
}

type NullableTrackFileLazyLoaded struct {
	value *TrackFileLazyLoaded
	isSet bool
}

func (v NullableTrackFileLazyLoaded) Get() *TrackFileLazyLoaded {
	return v.value
}

func (v *NullableTrackFileLazyLoaded) Set(val *TrackFileLazyLoaded) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackFileLazyLoaded) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackFileLazyLoaded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackFileLazyLoaded(val *TrackFileLazyLoaded) *NullableTrackFileLazyLoaded {
	return &NullableTrackFileLazyLoaded{value: val, isSet: true}
}

func (v NullableTrackFileLazyLoaded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackFileLazyLoaded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


