/*
Lidarr

Lidarr API docs

API version: v3.1.0.4875
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// checks if the ArtistEditorResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtistEditorResource{}

// ArtistEditorResource struct for ArtistEditorResource
type ArtistEditorResource struct {
	ArtistIds []int32 `json:"artistIds,omitempty"`
	Monitored NullableBool `json:"monitored,omitempty"`
	MonitorNewItems *NewItemMonitorTypes `json:"monitorNewItems,omitempty"`
	QualityProfileId NullableInt32 `json:"qualityProfileId,omitempty"`
	MetadataProfileId NullableInt32 `json:"metadataProfileId,omitempty"`
	RootFolderPath NullableString `json:"rootFolderPath,omitempty"`
	Tags []int32 `json:"tags,omitempty"`
	ApplyTags *ApplyTags `json:"applyTags,omitempty"`
	MoveFiles *bool `json:"moveFiles,omitempty"`
	DeleteFiles *bool `json:"deleteFiles,omitempty"`
	AddImportListExclusion *bool `json:"addImportListExclusion,omitempty"`
}

// NewArtistEditorResource instantiates a new ArtistEditorResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtistEditorResource() *ArtistEditorResource {
	this := ArtistEditorResource{}
	return &this
}

// NewArtistEditorResourceWithDefaults instantiates a new ArtistEditorResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtistEditorResourceWithDefaults() *ArtistEditorResource {
	this := ArtistEditorResource{}
	return &this
}

// GetArtistIds returns the ArtistIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetArtistIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.ArtistIds
}

// GetArtistIdsOk returns a tuple with the ArtistIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetArtistIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.ArtistIds) {
		return nil, false
	}
	return o.ArtistIds, true
}

// HasArtistIds returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasArtistIds() bool {
	if o != nil && !IsNil(o.ArtistIds) {
		return true
	}

	return false
}

// SetArtistIds gets a reference to the given []int32 and assigns it to the ArtistIds field.
func (o *ArtistEditorResource) SetArtistIds(v []int32) {
	o.ArtistIds = v
}

// GetMonitored returns the Monitored field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetMonitored() bool {
	if o == nil || IsNil(o.Monitored.Get()) {
		var ret bool
		return ret
	}
	return *o.Monitored.Get()
}

// GetMonitoredOk returns a tuple with the Monitored field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetMonitoredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Monitored.Get(), o.Monitored.IsSet()
}

// HasMonitored returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasMonitored() bool {
	if o != nil && o.Monitored.IsSet() {
		return true
	}

	return false
}

// SetMonitored gets a reference to the given NullableBool and assigns it to the Monitored field.
func (o *ArtistEditorResource) SetMonitored(v bool) {
	o.Monitored.Set(&v)
}
// SetMonitoredNil sets the value for Monitored to be an explicit nil
func (o *ArtistEditorResource) SetMonitoredNil() {
	o.Monitored.Set(nil)
}

// UnsetMonitored ensures that no value is present for Monitored, not even an explicit nil
func (o *ArtistEditorResource) UnsetMonitored() {
	o.Monitored.Unset()
}

// GetMonitorNewItems returns the MonitorNewItems field value if set, zero value otherwise.
func (o *ArtistEditorResource) GetMonitorNewItems() NewItemMonitorTypes {
	if o == nil || IsNil(o.MonitorNewItems) {
		var ret NewItemMonitorTypes
		return ret
	}
	return *o.MonitorNewItems
}

// GetMonitorNewItemsOk returns a tuple with the MonitorNewItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistEditorResource) GetMonitorNewItemsOk() (*NewItemMonitorTypes, bool) {
	if o == nil || IsNil(o.MonitorNewItems) {
		return nil, false
	}
	return o.MonitorNewItems, true
}

// HasMonitorNewItems returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasMonitorNewItems() bool {
	if o != nil && !IsNil(o.MonitorNewItems) {
		return true
	}

	return false
}

// SetMonitorNewItems gets a reference to the given NewItemMonitorTypes and assigns it to the MonitorNewItems field.
func (o *ArtistEditorResource) SetMonitorNewItems(v NewItemMonitorTypes) {
	o.MonitorNewItems = &v
}

// GetQualityProfileId returns the QualityProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetQualityProfileId() int32 {
	if o == nil || IsNil(o.QualityProfileId.Get()) {
		var ret int32
		return ret
	}
	return *o.QualityProfileId.Get()
}

// GetQualityProfileIdOk returns a tuple with the QualityProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetQualityProfileIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QualityProfileId.Get(), o.QualityProfileId.IsSet()
}

// HasQualityProfileId returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasQualityProfileId() bool {
	if o != nil && o.QualityProfileId.IsSet() {
		return true
	}

	return false
}

// SetQualityProfileId gets a reference to the given NullableInt32 and assigns it to the QualityProfileId field.
func (o *ArtistEditorResource) SetQualityProfileId(v int32) {
	o.QualityProfileId.Set(&v)
}
// SetQualityProfileIdNil sets the value for QualityProfileId to be an explicit nil
func (o *ArtistEditorResource) SetQualityProfileIdNil() {
	o.QualityProfileId.Set(nil)
}

// UnsetQualityProfileId ensures that no value is present for QualityProfileId, not even an explicit nil
func (o *ArtistEditorResource) UnsetQualityProfileId() {
	o.QualityProfileId.Unset()
}

// GetMetadataProfileId returns the MetadataProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetMetadataProfileId() int32 {
	if o == nil || IsNil(o.MetadataProfileId.Get()) {
		var ret int32
		return ret
	}
	return *o.MetadataProfileId.Get()
}

// GetMetadataProfileIdOk returns a tuple with the MetadataProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetMetadataProfileIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetadataProfileId.Get(), o.MetadataProfileId.IsSet()
}

// HasMetadataProfileId returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasMetadataProfileId() bool {
	if o != nil && o.MetadataProfileId.IsSet() {
		return true
	}

	return false
}

// SetMetadataProfileId gets a reference to the given NullableInt32 and assigns it to the MetadataProfileId field.
func (o *ArtistEditorResource) SetMetadataProfileId(v int32) {
	o.MetadataProfileId.Set(&v)
}
// SetMetadataProfileIdNil sets the value for MetadataProfileId to be an explicit nil
func (o *ArtistEditorResource) SetMetadataProfileIdNil() {
	o.MetadataProfileId.Set(nil)
}

// UnsetMetadataProfileId ensures that no value is present for MetadataProfileId, not even an explicit nil
func (o *ArtistEditorResource) UnsetMetadataProfileId() {
	o.MetadataProfileId.Unset()
}

// GetRootFolderPath returns the RootFolderPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetRootFolderPath() string {
	if o == nil || IsNil(o.RootFolderPath.Get()) {
		var ret string
		return ret
	}
	return *o.RootFolderPath.Get()
}

// GetRootFolderPathOk returns a tuple with the RootFolderPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetRootFolderPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RootFolderPath.Get(), o.RootFolderPath.IsSet()
}

// HasRootFolderPath returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasRootFolderPath() bool {
	if o != nil && o.RootFolderPath.IsSet() {
		return true
	}

	return false
}

// SetRootFolderPath gets a reference to the given NullableString and assigns it to the RootFolderPath field.
func (o *ArtistEditorResource) SetRootFolderPath(v string) {
	o.RootFolderPath.Set(&v)
}
// SetRootFolderPathNil sets the value for RootFolderPath to be an explicit nil
func (o *ArtistEditorResource) SetRootFolderPathNil() {
	o.RootFolderPath.Set(nil)
}

// UnsetRootFolderPath ensures that no value is present for RootFolderPath, not even an explicit nil
func (o *ArtistEditorResource) UnsetRootFolderPath() {
	o.RootFolderPath.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtistEditorResource) GetTags() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtistEditorResource) GetTagsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []int32 and assigns it to the Tags field.
func (o *ArtistEditorResource) SetTags(v []int32) {
	o.Tags = v
}

// GetApplyTags returns the ApplyTags field value if set, zero value otherwise.
func (o *ArtistEditorResource) GetApplyTags() ApplyTags {
	if o == nil || IsNil(o.ApplyTags) {
		var ret ApplyTags
		return ret
	}
	return *o.ApplyTags
}

// GetApplyTagsOk returns a tuple with the ApplyTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistEditorResource) GetApplyTagsOk() (*ApplyTags, bool) {
	if o == nil || IsNil(o.ApplyTags) {
		return nil, false
	}
	return o.ApplyTags, true
}

// HasApplyTags returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasApplyTags() bool {
	if o != nil && !IsNil(o.ApplyTags) {
		return true
	}

	return false
}

// SetApplyTags gets a reference to the given ApplyTags and assigns it to the ApplyTags field.
func (o *ArtistEditorResource) SetApplyTags(v ApplyTags) {
	o.ApplyTags = &v
}

// GetMoveFiles returns the MoveFiles field value if set, zero value otherwise.
func (o *ArtistEditorResource) GetMoveFiles() bool {
	if o == nil || IsNil(o.MoveFiles) {
		var ret bool
		return ret
	}
	return *o.MoveFiles
}

// GetMoveFilesOk returns a tuple with the MoveFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistEditorResource) GetMoveFilesOk() (*bool, bool) {
	if o == nil || IsNil(o.MoveFiles) {
		return nil, false
	}
	return o.MoveFiles, true
}

// HasMoveFiles returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasMoveFiles() bool {
	if o != nil && !IsNil(o.MoveFiles) {
		return true
	}

	return false
}

// SetMoveFiles gets a reference to the given bool and assigns it to the MoveFiles field.
func (o *ArtistEditorResource) SetMoveFiles(v bool) {
	o.MoveFiles = &v
}

// GetDeleteFiles returns the DeleteFiles field value if set, zero value otherwise.
func (o *ArtistEditorResource) GetDeleteFiles() bool {
	if o == nil || IsNil(o.DeleteFiles) {
		var ret bool
		return ret
	}
	return *o.DeleteFiles
}

// GetDeleteFilesOk returns a tuple with the DeleteFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistEditorResource) GetDeleteFilesOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteFiles) {
		return nil, false
	}
	return o.DeleteFiles, true
}

// HasDeleteFiles returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasDeleteFiles() bool {
	if o != nil && !IsNil(o.DeleteFiles) {
		return true
	}

	return false
}

// SetDeleteFiles gets a reference to the given bool and assigns it to the DeleteFiles field.
func (o *ArtistEditorResource) SetDeleteFiles(v bool) {
	o.DeleteFiles = &v
}

// GetAddImportListExclusion returns the AddImportListExclusion field value if set, zero value otherwise.
func (o *ArtistEditorResource) GetAddImportListExclusion() bool {
	if o == nil || IsNil(o.AddImportListExclusion) {
		var ret bool
		return ret
	}
	return *o.AddImportListExclusion
}

// GetAddImportListExclusionOk returns a tuple with the AddImportListExclusion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtistEditorResource) GetAddImportListExclusionOk() (*bool, bool) {
	if o == nil || IsNil(o.AddImportListExclusion) {
		return nil, false
	}
	return o.AddImportListExclusion, true
}

// HasAddImportListExclusion returns a boolean if a field has been set.
func (o *ArtistEditorResource) HasAddImportListExclusion() bool {
	if o != nil && !IsNil(o.AddImportListExclusion) {
		return true
	}

	return false
}

// SetAddImportListExclusion gets a reference to the given bool and assigns it to the AddImportListExclusion field.
func (o *ArtistEditorResource) SetAddImportListExclusion(v bool) {
	o.AddImportListExclusion = &v
}

func (o ArtistEditorResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtistEditorResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ArtistIds != nil {
		toSerialize["artistIds"] = o.ArtistIds
	}
	if o.Monitored.IsSet() {
		toSerialize["monitored"] = o.Monitored.Get()
	}
	if !IsNil(o.MonitorNewItems) {
		toSerialize["monitorNewItems"] = o.MonitorNewItems
	}
	if o.QualityProfileId.IsSet() {
		toSerialize["qualityProfileId"] = o.QualityProfileId.Get()
	}
	if o.MetadataProfileId.IsSet() {
		toSerialize["metadataProfileId"] = o.MetadataProfileId.Get()
	}
	if o.RootFolderPath.IsSet() {
		toSerialize["rootFolderPath"] = o.RootFolderPath.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.ApplyTags) {
		toSerialize["applyTags"] = o.ApplyTags
	}
	if !IsNil(o.MoveFiles) {
		toSerialize["moveFiles"] = o.MoveFiles
	}
	if !IsNil(o.DeleteFiles) {
		toSerialize["deleteFiles"] = o.DeleteFiles
	}
	if !IsNil(o.AddImportListExclusion) {
		toSerialize["addImportListExclusion"] = o.AddImportListExclusion
	}
	return toSerialize, nil
}

type NullableArtistEditorResource struct {
	value *ArtistEditorResource
	isSet bool
}

func (v NullableArtistEditorResource) Get() *ArtistEditorResource {
	return v.value
}

func (v *NullableArtistEditorResource) Set(val *ArtistEditorResource) {
	v.value = val
	v.isSet = true
}

func (v NullableArtistEditorResource) IsSet() bool {
	return v.isSet
}

func (v *NullableArtistEditorResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtistEditorResource(val *ArtistEditorResource) *NullableArtistEditorResource {
	return &NullableArtistEditorResource{value: val, isSet: true}
}

func (v NullableArtistEditorResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtistEditorResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


