/*
Lidarr

Lidarr API docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// AlbumReleaseListLazyLoaded struct for AlbumReleaseListLazyLoaded
type AlbumReleaseListLazyLoaded struct {
	Value []*AlbumRelease `json:"value,omitempty"`
	IsLoaded *bool `json:"isLoaded,omitempty"`
}

// NewAlbumReleaseListLazyLoaded instantiates a new AlbumReleaseListLazyLoaded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlbumReleaseListLazyLoaded() *AlbumReleaseListLazyLoaded {
	this := AlbumReleaseListLazyLoaded{}
	return &this
}

// NewAlbumReleaseListLazyLoadedWithDefaults instantiates a new AlbumReleaseListLazyLoaded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlbumReleaseListLazyLoadedWithDefaults() *AlbumReleaseListLazyLoaded {
	this := AlbumReleaseListLazyLoaded{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AlbumReleaseListLazyLoaded) GetValue() []*AlbumRelease {
	if o == nil {
		var ret []*AlbumRelease
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AlbumReleaseListLazyLoaded) GetValueOk() ([]*AlbumRelease, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AlbumReleaseListLazyLoaded) HasValue() bool {
	if o != nil && isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []AlbumRelease and assigns it to the Value field.
func (o *AlbumReleaseListLazyLoaded) SetValue(v []*AlbumRelease) {
	o.Value = v
}

// GetIsLoaded returns the IsLoaded field value if set, zero value otherwise.
func (o *AlbumReleaseListLazyLoaded) GetIsLoaded() bool {
	if o == nil || isNil(o.IsLoaded) {
		var ret bool
		return ret
	}
	return *o.IsLoaded
}

// GetIsLoadedOk returns a tuple with the IsLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlbumReleaseListLazyLoaded) GetIsLoadedOk() (*bool, bool) {
	if o == nil || isNil(o.IsLoaded) {
    return nil, false
	}
	return o.IsLoaded, true
}

// HasIsLoaded returns a boolean if a field has been set.
func (o *AlbumReleaseListLazyLoaded) HasIsLoaded() bool {
	if o != nil && !isNil(o.IsLoaded) {
		return true
	}

	return false
}

// SetIsLoaded gets a reference to the given bool and assigns it to the IsLoaded field.
func (o *AlbumReleaseListLazyLoaded) SetIsLoaded(v bool) {
	o.IsLoaded = &v
}

func (o AlbumReleaseListLazyLoaded) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if !isNil(o.IsLoaded) {
		toSerialize["isLoaded"] = o.IsLoaded
	}
	return json.Marshal(toSerialize)
}

type NullableAlbumReleaseListLazyLoaded struct {
	value *AlbumReleaseListLazyLoaded
	isSet bool
}

func (v NullableAlbumReleaseListLazyLoaded) Get() *AlbumReleaseListLazyLoaded {
	return v.value
}

func (v *NullableAlbumReleaseListLazyLoaded) Set(val *AlbumReleaseListLazyLoaded) {
	v.value = val
	v.isSet = true
}

func (v NullableAlbumReleaseListLazyLoaded) IsSet() bool {
	return v.isSet
}

func (v *NullableAlbumReleaseListLazyLoaded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlbumReleaseListLazyLoaded(val *AlbumReleaseListLazyLoaded) *NullableAlbumReleaseListLazyLoaded {
	return &NullableAlbumReleaseListLazyLoaded{value: val, isSet: true}
}

func (v NullableAlbumReleaseListLazyLoaded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlbumReleaseListLazyLoaded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


