/*
Lidarr

Lidarr API docs

API version: v2.1.7.4030
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// ProfileReleaseStatusItemResource struct for ProfileReleaseStatusItemResource
type ProfileReleaseStatusItemResource struct {
	Id *int32 `json:"id,omitempty"`
	ReleaseStatus *ReleaseStatus `json:"releaseStatus,omitempty"`
	Allowed *bool `json:"allowed,omitempty"`
}

// NewProfileReleaseStatusItemResource instantiates a new ProfileReleaseStatusItemResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileReleaseStatusItemResource() *ProfileReleaseStatusItemResource {
	this := ProfileReleaseStatusItemResource{}
	return &this
}

// NewProfileReleaseStatusItemResourceWithDefaults instantiates a new ProfileReleaseStatusItemResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileReleaseStatusItemResourceWithDefaults() *ProfileReleaseStatusItemResource {
	this := ProfileReleaseStatusItemResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProfileReleaseStatusItemResource) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileReleaseStatusItemResource) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProfileReleaseStatusItemResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProfileReleaseStatusItemResource) SetId(v int32) {
	o.Id = &v
}

// GetReleaseStatus returns the ReleaseStatus field value if set, zero value otherwise.
func (o *ProfileReleaseStatusItemResource) GetReleaseStatus() ReleaseStatus {
	if o == nil || isNil(o.ReleaseStatus) {
		var ret ReleaseStatus
		return ret
	}
	return *o.ReleaseStatus
}

// GetReleaseStatusOk returns a tuple with the ReleaseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileReleaseStatusItemResource) GetReleaseStatusOk() (*ReleaseStatus, bool) {
	if o == nil || isNil(o.ReleaseStatus) {
    return nil, false
	}
	return o.ReleaseStatus, true
}

// HasReleaseStatus returns a boolean if a field has been set.
func (o *ProfileReleaseStatusItemResource) HasReleaseStatus() bool {
	if o != nil && !isNil(o.ReleaseStatus) {
		return true
	}

	return false
}

// SetReleaseStatus gets a reference to the given ReleaseStatus and assigns it to the ReleaseStatus field.
func (o *ProfileReleaseStatusItemResource) SetReleaseStatus(v ReleaseStatus) {
	o.ReleaseStatus = &v
}

// GetAllowed returns the Allowed field value if set, zero value otherwise.
func (o *ProfileReleaseStatusItemResource) GetAllowed() bool {
	if o == nil || isNil(o.Allowed) {
		var ret bool
		return ret
	}
	return *o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileReleaseStatusItemResource) GetAllowedOk() (*bool, bool) {
	if o == nil || isNil(o.Allowed) {
    return nil, false
	}
	return o.Allowed, true
}

// HasAllowed returns a boolean if a field has been set.
func (o *ProfileReleaseStatusItemResource) HasAllowed() bool {
	if o != nil && !isNil(o.Allowed) {
		return true
	}

	return false
}

// SetAllowed gets a reference to the given bool and assigns it to the Allowed field.
func (o *ProfileReleaseStatusItemResource) SetAllowed(v bool) {
	o.Allowed = &v
}

func (o ProfileReleaseStatusItemResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.ReleaseStatus) {
		toSerialize["releaseStatus"] = o.ReleaseStatus
	}
	if !isNil(o.Allowed) {
		toSerialize["allowed"] = o.Allowed
	}
	return json.Marshal(toSerialize)
}

type NullableProfileReleaseStatusItemResource struct {
	value *ProfileReleaseStatusItemResource
	isSet bool
}

func (v NullableProfileReleaseStatusItemResource) Get() *ProfileReleaseStatusItemResource {
	return v.value
}

func (v *NullableProfileReleaseStatusItemResource) Set(val *ProfileReleaseStatusItemResource) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileReleaseStatusItemResource) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileReleaseStatusItemResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileReleaseStatusItemResource(val *ProfileReleaseStatusItemResource) *NullableProfileReleaseStatusItemResource {
	return &NullableProfileReleaseStatusItemResource{value: val, isSet: true}
}

func (v NullableProfileReleaseStatusItemResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileReleaseStatusItemResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


