/*
Lidarr

Lidarr API docs

API version: v2.1.7.4030
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lidarr

import (
	"encoding/json"
)

// checks if the ParsedTrackInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParsedTrackInfo{}

// ParsedTrackInfo struct for ParsedTrackInfo
type ParsedTrackInfo struct {
	Title NullableString `json:"title,omitempty"`
	CleanTitle NullableString `json:"cleanTitle,omitempty"`
	ArtistTitle NullableString `json:"artistTitle,omitempty"`
	AlbumTitle NullableString `json:"albumTitle,omitempty"`
	ArtistTitleInfo *ArtistTitleInfo `json:"artistTitleInfo,omitempty"`
	ArtistMBId NullableString `json:"artistMBId,omitempty"`
	AlbumMBId NullableString `json:"albumMBId,omitempty"`
	ReleaseMBId NullableString `json:"releaseMBId,omitempty"`
	RecordingMBId NullableString `json:"recordingMBId,omitempty"`
	TrackMBId NullableString `json:"trackMBId,omitempty"`
	DiscNumber *int32 `json:"discNumber,omitempty"`
	DiscCount *int32 `json:"discCount,omitempty"`
	Country *IsoCountry `json:"country,omitempty"`
	Year *int32 `json:"year,omitempty"`
	Label NullableString `json:"label,omitempty"`
	CatalogNumber NullableString `json:"catalogNumber,omitempty"`
	Disambiguation NullableString `json:"disambiguation,omitempty"`
	Duration *string `json:"duration,omitempty"`
	Quality *QualityModel `json:"quality,omitempty"`
	MediaInfo *MediaInfoModel `json:"mediaInfo,omitempty"`
	TrackNumbers []int32 `json:"trackNumbers,omitempty"`
	ReleaseGroup NullableString `json:"releaseGroup,omitempty"`
	ReleaseHash NullableString `json:"releaseHash,omitempty"`
}

// NewParsedTrackInfo instantiates a new ParsedTrackInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParsedTrackInfo() *ParsedTrackInfo {
	this := ParsedTrackInfo{}
	return &this
}

// NewParsedTrackInfoWithDefaults instantiates a new ParsedTrackInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParsedTrackInfoWithDefaults() *ParsedTrackInfo {
	this := ParsedTrackInfo{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ParsedTrackInfo) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ParsedTrackInfo) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ParsedTrackInfo) UnsetTitle() {
	o.Title.Unset()
}

// GetCleanTitle returns the CleanTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetCleanTitle() string {
	if o == nil || IsNil(o.CleanTitle.Get()) {
		var ret string
		return ret
	}
	return *o.CleanTitle.Get()
}

// GetCleanTitleOk returns a tuple with the CleanTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetCleanTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CleanTitle.Get(), o.CleanTitle.IsSet()
}

// HasCleanTitle returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasCleanTitle() bool {
	if o != nil && o.CleanTitle.IsSet() {
		return true
	}

	return false
}

// SetCleanTitle gets a reference to the given NullableString and assigns it to the CleanTitle field.
func (o *ParsedTrackInfo) SetCleanTitle(v string) {
	o.CleanTitle.Set(&v)
}
// SetCleanTitleNil sets the value for CleanTitle to be an explicit nil
func (o *ParsedTrackInfo) SetCleanTitleNil() {
	o.CleanTitle.Set(nil)
}

// UnsetCleanTitle ensures that no value is present for CleanTitle, not even an explicit nil
func (o *ParsedTrackInfo) UnsetCleanTitle() {
	o.CleanTitle.Unset()
}

// GetArtistTitle returns the ArtistTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetArtistTitle() string {
	if o == nil || IsNil(o.ArtistTitle.Get()) {
		var ret string
		return ret
	}
	return *o.ArtistTitle.Get()
}

// GetArtistTitleOk returns a tuple with the ArtistTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetArtistTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtistTitle.Get(), o.ArtistTitle.IsSet()
}

// HasArtistTitle returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasArtistTitle() bool {
	if o != nil && o.ArtistTitle.IsSet() {
		return true
	}

	return false
}

// SetArtistTitle gets a reference to the given NullableString and assigns it to the ArtistTitle field.
func (o *ParsedTrackInfo) SetArtistTitle(v string) {
	o.ArtistTitle.Set(&v)
}
// SetArtistTitleNil sets the value for ArtistTitle to be an explicit nil
func (o *ParsedTrackInfo) SetArtistTitleNil() {
	o.ArtistTitle.Set(nil)
}

// UnsetArtistTitle ensures that no value is present for ArtistTitle, not even an explicit nil
func (o *ParsedTrackInfo) UnsetArtistTitle() {
	o.ArtistTitle.Unset()
}

// GetAlbumTitle returns the AlbumTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetAlbumTitle() string {
	if o == nil || IsNil(o.AlbumTitle.Get()) {
		var ret string
		return ret
	}
	return *o.AlbumTitle.Get()
}

// GetAlbumTitleOk returns a tuple with the AlbumTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetAlbumTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlbumTitle.Get(), o.AlbumTitle.IsSet()
}

// HasAlbumTitle returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasAlbumTitle() bool {
	if o != nil && o.AlbumTitle.IsSet() {
		return true
	}

	return false
}

// SetAlbumTitle gets a reference to the given NullableString and assigns it to the AlbumTitle field.
func (o *ParsedTrackInfo) SetAlbumTitle(v string) {
	o.AlbumTitle.Set(&v)
}
// SetAlbumTitleNil sets the value for AlbumTitle to be an explicit nil
func (o *ParsedTrackInfo) SetAlbumTitleNil() {
	o.AlbumTitle.Set(nil)
}

// UnsetAlbumTitle ensures that no value is present for AlbumTitle, not even an explicit nil
func (o *ParsedTrackInfo) UnsetAlbumTitle() {
	o.AlbumTitle.Unset()
}

// GetArtistTitleInfo returns the ArtistTitleInfo field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetArtistTitleInfo() ArtistTitleInfo {
	if o == nil || IsNil(o.ArtistTitleInfo) {
		var ret ArtistTitleInfo
		return ret
	}
	return *o.ArtistTitleInfo
}

// GetArtistTitleInfoOk returns a tuple with the ArtistTitleInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetArtistTitleInfoOk() (*ArtistTitleInfo, bool) {
	if o == nil || IsNil(o.ArtistTitleInfo) {
		return nil, false
	}
	return o.ArtistTitleInfo, true
}

// HasArtistTitleInfo returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasArtistTitleInfo() bool {
	if o != nil && !IsNil(o.ArtistTitleInfo) {
		return true
	}

	return false
}

// SetArtistTitleInfo gets a reference to the given ArtistTitleInfo and assigns it to the ArtistTitleInfo field.
func (o *ParsedTrackInfo) SetArtistTitleInfo(v ArtistTitleInfo) {
	o.ArtistTitleInfo = &v
}

// GetArtistMBId returns the ArtistMBId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetArtistMBId() string {
	if o == nil || IsNil(o.ArtistMBId.Get()) {
		var ret string
		return ret
	}
	return *o.ArtistMBId.Get()
}

// GetArtistMBIdOk returns a tuple with the ArtistMBId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetArtistMBIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtistMBId.Get(), o.ArtistMBId.IsSet()
}

// HasArtistMBId returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasArtistMBId() bool {
	if o != nil && o.ArtistMBId.IsSet() {
		return true
	}

	return false
}

// SetArtistMBId gets a reference to the given NullableString and assigns it to the ArtistMBId field.
func (o *ParsedTrackInfo) SetArtistMBId(v string) {
	o.ArtistMBId.Set(&v)
}
// SetArtistMBIdNil sets the value for ArtistMBId to be an explicit nil
func (o *ParsedTrackInfo) SetArtistMBIdNil() {
	o.ArtistMBId.Set(nil)
}

// UnsetArtistMBId ensures that no value is present for ArtistMBId, not even an explicit nil
func (o *ParsedTrackInfo) UnsetArtistMBId() {
	o.ArtistMBId.Unset()
}

// GetAlbumMBId returns the AlbumMBId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetAlbumMBId() string {
	if o == nil || IsNil(o.AlbumMBId.Get()) {
		var ret string
		return ret
	}
	return *o.AlbumMBId.Get()
}

// GetAlbumMBIdOk returns a tuple with the AlbumMBId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetAlbumMBIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlbumMBId.Get(), o.AlbumMBId.IsSet()
}

// HasAlbumMBId returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasAlbumMBId() bool {
	if o != nil && o.AlbumMBId.IsSet() {
		return true
	}

	return false
}

// SetAlbumMBId gets a reference to the given NullableString and assigns it to the AlbumMBId field.
func (o *ParsedTrackInfo) SetAlbumMBId(v string) {
	o.AlbumMBId.Set(&v)
}
// SetAlbumMBIdNil sets the value for AlbumMBId to be an explicit nil
func (o *ParsedTrackInfo) SetAlbumMBIdNil() {
	o.AlbumMBId.Set(nil)
}

// UnsetAlbumMBId ensures that no value is present for AlbumMBId, not even an explicit nil
func (o *ParsedTrackInfo) UnsetAlbumMBId() {
	o.AlbumMBId.Unset()
}

// GetReleaseMBId returns the ReleaseMBId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetReleaseMBId() string {
	if o == nil || IsNil(o.ReleaseMBId.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseMBId.Get()
}

// GetReleaseMBIdOk returns a tuple with the ReleaseMBId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetReleaseMBIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReleaseMBId.Get(), o.ReleaseMBId.IsSet()
}

// HasReleaseMBId returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasReleaseMBId() bool {
	if o != nil && o.ReleaseMBId.IsSet() {
		return true
	}

	return false
}

// SetReleaseMBId gets a reference to the given NullableString and assigns it to the ReleaseMBId field.
func (o *ParsedTrackInfo) SetReleaseMBId(v string) {
	o.ReleaseMBId.Set(&v)
}
// SetReleaseMBIdNil sets the value for ReleaseMBId to be an explicit nil
func (o *ParsedTrackInfo) SetReleaseMBIdNil() {
	o.ReleaseMBId.Set(nil)
}

// UnsetReleaseMBId ensures that no value is present for ReleaseMBId, not even an explicit nil
func (o *ParsedTrackInfo) UnsetReleaseMBId() {
	o.ReleaseMBId.Unset()
}

// GetRecordingMBId returns the RecordingMBId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetRecordingMBId() string {
	if o == nil || IsNil(o.RecordingMBId.Get()) {
		var ret string
		return ret
	}
	return *o.RecordingMBId.Get()
}

// GetRecordingMBIdOk returns a tuple with the RecordingMBId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetRecordingMBIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecordingMBId.Get(), o.RecordingMBId.IsSet()
}

// HasRecordingMBId returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasRecordingMBId() bool {
	if o != nil && o.RecordingMBId.IsSet() {
		return true
	}

	return false
}

// SetRecordingMBId gets a reference to the given NullableString and assigns it to the RecordingMBId field.
func (o *ParsedTrackInfo) SetRecordingMBId(v string) {
	o.RecordingMBId.Set(&v)
}
// SetRecordingMBIdNil sets the value for RecordingMBId to be an explicit nil
func (o *ParsedTrackInfo) SetRecordingMBIdNil() {
	o.RecordingMBId.Set(nil)
}

// UnsetRecordingMBId ensures that no value is present for RecordingMBId, not even an explicit nil
func (o *ParsedTrackInfo) UnsetRecordingMBId() {
	o.RecordingMBId.Unset()
}

// GetTrackMBId returns the TrackMBId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetTrackMBId() string {
	if o == nil || IsNil(o.TrackMBId.Get()) {
		var ret string
		return ret
	}
	return *o.TrackMBId.Get()
}

// GetTrackMBIdOk returns a tuple with the TrackMBId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetTrackMBIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrackMBId.Get(), o.TrackMBId.IsSet()
}

// HasTrackMBId returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasTrackMBId() bool {
	if o != nil && o.TrackMBId.IsSet() {
		return true
	}

	return false
}

// SetTrackMBId gets a reference to the given NullableString and assigns it to the TrackMBId field.
func (o *ParsedTrackInfo) SetTrackMBId(v string) {
	o.TrackMBId.Set(&v)
}
// SetTrackMBIdNil sets the value for TrackMBId to be an explicit nil
func (o *ParsedTrackInfo) SetTrackMBIdNil() {
	o.TrackMBId.Set(nil)
}

// UnsetTrackMBId ensures that no value is present for TrackMBId, not even an explicit nil
func (o *ParsedTrackInfo) UnsetTrackMBId() {
	o.TrackMBId.Unset()
}

// GetDiscNumber returns the DiscNumber field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetDiscNumber() int32 {
	if o == nil || IsNil(o.DiscNumber) {
		var ret int32
		return ret
	}
	return *o.DiscNumber
}

// GetDiscNumberOk returns a tuple with the DiscNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetDiscNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.DiscNumber) {
		return nil, false
	}
	return o.DiscNumber, true
}

// HasDiscNumber returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasDiscNumber() bool {
	if o != nil && !IsNil(o.DiscNumber) {
		return true
	}

	return false
}

// SetDiscNumber gets a reference to the given int32 and assigns it to the DiscNumber field.
func (o *ParsedTrackInfo) SetDiscNumber(v int32) {
	o.DiscNumber = &v
}

// GetDiscCount returns the DiscCount field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetDiscCount() int32 {
	if o == nil || IsNil(o.DiscCount) {
		var ret int32
		return ret
	}
	return *o.DiscCount
}

// GetDiscCountOk returns a tuple with the DiscCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetDiscCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DiscCount) {
		return nil, false
	}
	return o.DiscCount, true
}

// HasDiscCount returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasDiscCount() bool {
	if o != nil && !IsNil(o.DiscCount) {
		return true
	}

	return false
}

// SetDiscCount gets a reference to the given int32 and assigns it to the DiscCount field.
func (o *ParsedTrackInfo) SetDiscCount(v int32) {
	o.DiscCount = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetCountry() IsoCountry {
	if o == nil || IsNil(o.Country) {
		var ret IsoCountry
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetCountryOk() (*IsoCountry, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given IsoCountry and assigns it to the Country field.
func (o *ParsedTrackInfo) SetCountry(v IsoCountry) {
	o.Country = &v
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetYear() int32 {
	if o == nil || IsNil(o.Year) {
		var ret int32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetYearOk() (*int32, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given int32 and assigns it to the Year field.
func (o *ParsedTrackInfo) SetYear(v int32) {
	o.Year = &v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *ParsedTrackInfo) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *ParsedTrackInfo) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *ParsedTrackInfo) UnsetLabel() {
	o.Label.Unset()
}

// GetCatalogNumber returns the CatalogNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetCatalogNumber() string {
	if o == nil || IsNil(o.CatalogNumber.Get()) {
		var ret string
		return ret
	}
	return *o.CatalogNumber.Get()
}

// GetCatalogNumberOk returns a tuple with the CatalogNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetCatalogNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CatalogNumber.Get(), o.CatalogNumber.IsSet()
}

// HasCatalogNumber returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasCatalogNumber() bool {
	if o != nil && o.CatalogNumber.IsSet() {
		return true
	}

	return false
}

// SetCatalogNumber gets a reference to the given NullableString and assigns it to the CatalogNumber field.
func (o *ParsedTrackInfo) SetCatalogNumber(v string) {
	o.CatalogNumber.Set(&v)
}
// SetCatalogNumberNil sets the value for CatalogNumber to be an explicit nil
func (o *ParsedTrackInfo) SetCatalogNumberNil() {
	o.CatalogNumber.Set(nil)
}

// UnsetCatalogNumber ensures that no value is present for CatalogNumber, not even an explicit nil
func (o *ParsedTrackInfo) UnsetCatalogNumber() {
	o.CatalogNumber.Unset()
}

// GetDisambiguation returns the Disambiguation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetDisambiguation() string {
	if o == nil || IsNil(o.Disambiguation.Get()) {
		var ret string
		return ret
	}
	return *o.Disambiguation.Get()
}

// GetDisambiguationOk returns a tuple with the Disambiguation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetDisambiguationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disambiguation.Get(), o.Disambiguation.IsSet()
}

// HasDisambiguation returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasDisambiguation() bool {
	if o != nil && o.Disambiguation.IsSet() {
		return true
	}

	return false
}

// SetDisambiguation gets a reference to the given NullableString and assigns it to the Disambiguation field.
func (o *ParsedTrackInfo) SetDisambiguation(v string) {
	o.Disambiguation.Set(&v)
}
// SetDisambiguationNil sets the value for Disambiguation to be an explicit nil
func (o *ParsedTrackInfo) SetDisambiguationNil() {
	o.Disambiguation.Set(nil)
}

// UnsetDisambiguation ensures that no value is present for Disambiguation, not even an explicit nil
func (o *ParsedTrackInfo) UnsetDisambiguation() {
	o.Disambiguation.Unset()
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *ParsedTrackInfo) SetDuration(v string) {
	o.Duration = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetQuality() QualityModel {
	if o == nil || IsNil(o.Quality) {
		var ret QualityModel
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetQualityOk() (*QualityModel, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given QualityModel and assigns it to the Quality field.
func (o *ParsedTrackInfo) SetQuality(v QualityModel) {
	o.Quality = &v
}

// GetMediaInfo returns the MediaInfo field value if set, zero value otherwise.
func (o *ParsedTrackInfo) GetMediaInfo() MediaInfoModel {
	if o == nil || IsNil(o.MediaInfo) {
		var ret MediaInfoModel
		return ret
	}
	return *o.MediaInfo
}

// GetMediaInfoOk returns a tuple with the MediaInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParsedTrackInfo) GetMediaInfoOk() (*MediaInfoModel, bool) {
	if o == nil || IsNil(o.MediaInfo) {
		return nil, false
	}
	return o.MediaInfo, true
}

// HasMediaInfo returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasMediaInfo() bool {
	if o != nil && !IsNil(o.MediaInfo) {
		return true
	}

	return false
}

// SetMediaInfo gets a reference to the given MediaInfoModel and assigns it to the MediaInfo field.
func (o *ParsedTrackInfo) SetMediaInfo(v MediaInfoModel) {
	o.MediaInfo = &v
}

// GetTrackNumbers returns the TrackNumbers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetTrackNumbers() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.TrackNumbers
}

// GetTrackNumbersOk returns a tuple with the TrackNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetTrackNumbersOk() ([]int32, bool) {
	if o == nil || IsNil(o.TrackNumbers) {
		return nil, false
	}
	return o.TrackNumbers, true
}

// HasTrackNumbers returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasTrackNumbers() bool {
	if o != nil && !IsNil(o.TrackNumbers) {
		return true
	}

	return false
}

// SetTrackNumbers gets a reference to the given []int32 and assigns it to the TrackNumbers field.
func (o *ParsedTrackInfo) SetTrackNumbers(v []int32) {
	o.TrackNumbers = v
}

// GetReleaseGroup returns the ReleaseGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetReleaseGroup() string {
	if o == nil || IsNil(o.ReleaseGroup.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseGroup.Get()
}

// GetReleaseGroupOk returns a tuple with the ReleaseGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetReleaseGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReleaseGroup.Get(), o.ReleaseGroup.IsSet()
}

// HasReleaseGroup returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasReleaseGroup() bool {
	if o != nil && o.ReleaseGroup.IsSet() {
		return true
	}

	return false
}

// SetReleaseGroup gets a reference to the given NullableString and assigns it to the ReleaseGroup field.
func (o *ParsedTrackInfo) SetReleaseGroup(v string) {
	o.ReleaseGroup.Set(&v)
}
// SetReleaseGroupNil sets the value for ReleaseGroup to be an explicit nil
func (o *ParsedTrackInfo) SetReleaseGroupNil() {
	o.ReleaseGroup.Set(nil)
}

// UnsetReleaseGroup ensures that no value is present for ReleaseGroup, not even an explicit nil
func (o *ParsedTrackInfo) UnsetReleaseGroup() {
	o.ReleaseGroup.Unset()
}

// GetReleaseHash returns the ReleaseHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParsedTrackInfo) GetReleaseHash() string {
	if o == nil || IsNil(o.ReleaseHash.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseHash.Get()
}

// GetReleaseHashOk returns a tuple with the ReleaseHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParsedTrackInfo) GetReleaseHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReleaseHash.Get(), o.ReleaseHash.IsSet()
}

// HasReleaseHash returns a boolean if a field has been set.
func (o *ParsedTrackInfo) HasReleaseHash() bool {
	if o != nil && o.ReleaseHash.IsSet() {
		return true
	}

	return false
}

// SetReleaseHash gets a reference to the given NullableString and assigns it to the ReleaseHash field.
func (o *ParsedTrackInfo) SetReleaseHash(v string) {
	o.ReleaseHash.Set(&v)
}
// SetReleaseHashNil sets the value for ReleaseHash to be an explicit nil
func (o *ParsedTrackInfo) SetReleaseHashNil() {
	o.ReleaseHash.Set(nil)
}

// UnsetReleaseHash ensures that no value is present for ReleaseHash, not even an explicit nil
func (o *ParsedTrackInfo) UnsetReleaseHash() {
	o.ReleaseHash.Unset()
}

func (o ParsedTrackInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParsedTrackInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.CleanTitle.IsSet() {
		toSerialize["cleanTitle"] = o.CleanTitle.Get()
	}
	if o.ArtistTitle.IsSet() {
		toSerialize["artistTitle"] = o.ArtistTitle.Get()
	}
	if o.AlbumTitle.IsSet() {
		toSerialize["albumTitle"] = o.AlbumTitle.Get()
	}
	if !IsNil(o.ArtistTitleInfo) {
		toSerialize["artistTitleInfo"] = o.ArtistTitleInfo
	}
	if o.ArtistMBId.IsSet() {
		toSerialize["artistMBId"] = o.ArtistMBId.Get()
	}
	if o.AlbumMBId.IsSet() {
		toSerialize["albumMBId"] = o.AlbumMBId.Get()
	}
	if o.ReleaseMBId.IsSet() {
		toSerialize["releaseMBId"] = o.ReleaseMBId.Get()
	}
	if o.RecordingMBId.IsSet() {
		toSerialize["recordingMBId"] = o.RecordingMBId.Get()
	}
	if o.TrackMBId.IsSet() {
		toSerialize["trackMBId"] = o.TrackMBId.Get()
	}
	if !IsNil(o.DiscNumber) {
		toSerialize["discNumber"] = o.DiscNumber
	}
	if !IsNil(o.DiscCount) {
		toSerialize["discCount"] = o.DiscCount
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.CatalogNumber.IsSet() {
		toSerialize["catalogNumber"] = o.CatalogNumber.Get()
	}
	if o.Disambiguation.IsSet() {
		toSerialize["disambiguation"] = o.Disambiguation.Get()
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !IsNil(o.MediaInfo) {
		toSerialize["mediaInfo"] = o.MediaInfo
	}
	if o.TrackNumbers != nil {
		toSerialize["trackNumbers"] = o.TrackNumbers
	}
	if o.ReleaseGroup.IsSet() {
		toSerialize["releaseGroup"] = o.ReleaseGroup.Get()
	}
	if o.ReleaseHash.IsSet() {
		toSerialize["releaseHash"] = o.ReleaseHash.Get()
	}
	return toSerialize, nil
}

type NullableParsedTrackInfo struct {
	value *ParsedTrackInfo
	isSet bool
}

func (v NullableParsedTrackInfo) Get() *ParsedTrackInfo {
	return v.value
}

func (v *NullableParsedTrackInfo) Set(val *ParsedTrackInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableParsedTrackInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableParsedTrackInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParsedTrackInfo(val *ParsedTrackInfo) *NullableParsedTrackInfo {
	return &NullableParsedTrackInfo{value: val, isSet: true}
}

func (v NullableParsedTrackInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParsedTrackInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


